[package]
name = "tsp-rust"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "random_search"
path = "bin/random_search.rs"

[dependencies] # TODO: update version numbers
rand = "0.8"
rand_chacha = "0.3"